site_name: Eccomerce-ED
nav:
  - Home: index.md
  - Padrões do Projeto: padroes.md
  - Ferramentas: ferramentas.md
  - Arquitetura: arquitetura.md
  - ETL: etl.md
  - Dashboard: dashboard.md
theme:
  name: dracula
