name: Feature request
description: Suggest an idea for this project
title: "[FEAT]: "
labels: ["enhancement", "question"]
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide the following information:

  - type: input
    id: title
    attributes:
      label: Title
      description: A brief title for your feature request
      placeholder: Feature title
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A detailed description of the feature request
      placeholder: Describe the feature
    validations:
      required: true

  - type: dropdown
    id: importance
    attributes:
      label: Importance
      description: How important is this feature to you?
      options:
        - Low
        - Medium
        - High
    validations:
      required: true