services:
  database_dimensional:
    image: postgres
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      POSTGRES_PASSWORD: "pass@"
    ports:
      - "5438:5432"